### PR TITLE
Issue 166: incorrect code for condition_occurrence.condition_type_con…

### PR DESCRIPTION
**Pull request by mgkahn**
Fixes OHDSI/ETL-Synthea#166

Replaces incorrect code for condition_occurrence.condition_type_concept_id.sql for both cdm v531 and v540 (38000175 -->32020)

### CODE REVIEW

**Comment by burrowse** [comment]
@mgkahn Thanks so much for looking into this! The [38000175 - Prescription dispensed in pharmacy](https://athena.ohdsi.org/search-terms/terms/38000175) is definitely an error and needs to be updated. However, the concept [32020- EHR encounter diagnosis](https://athena.ohdsi.org/search-terms/terms/32020) currently maps to a non-standard concept in the `Condition Type` domain where as the [specifications](https://ohdsi.github.io/CommonDataModel/cdm54.html#CONDITION_OCCURRENCE) call for a standard concept from the `Type Concept` domain. Would another standarad concept from the `Type Concept` domain such as [32827 - EHR encounter record](https://athena.ohdsi.org/search-terms/terms/32827) be appropriate here?

**Comment by mgkahn** [comment]
@burrowse Oops. I did not check for being a standard concept_id when I selected concept_id = 32020 (gotta change this in our ETL pipeline........). I think 32827 fits the same intention and is standard as you noted so I agree this is a better code to use.

**Comment by burrowse** [comment]
@mgkahn Okay sounds good! It looks like this change is currently on a local fork, do you want to make the change there (and in your pipeline)? From there we should be able to get this merged in :)

**Comment by mgkahn** [comment]
I have never updated a pending/open PR but I think I followed the instructions I found on Google. Let me know if you can see the change to 32020. Also, I wondered how I got 32020 in the first place and I see that it was mentioned in the ETL-Synthea documentation. So I added changes to the HTML for condition_occurrence to refelct 32827. Let me know if the updated changes are now in the current PR or if I need to do an additional step. This is my Github ignorance showing.

**Review by burrowse — APPROVED** [review]
Looks good! Thanks for making those additional updates!

**Pull request merged**
